import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = file => readFile(path.join(root, file), 'utf8');
const modules = ['fade', 'particle', 'consultation'];
const code = await Promise.all(modules.map(name => read(`js/modules/${name}.js`)));
const main = (await read('js/main.js')).replace(/^import .*;\s*$/gm, '');
const bundle = '// Generated by npm run build:preview; edit js/modules and js/main.js instead.\n' + code.map(source => source.replace(/^export /gm, '')).join('\n') + '\n' + main;
const html = (await read('index.html')).replace('<script type="module" src="js/main.js"></script>', '<script defer src="js/preview.js"></script>');
await writeFile(path.join(root, 'js/preview.js'), bundle);
await writeFile(path.join(root, 'preview.html'), '<!-- Generated preview: edit index.html, then run npm run build. -->\n' + html);
console.log('Generated preview.html and js/preview.js for direct browser opening.');
